### ISSUE TITLE
Handle evolutive layouts

### ISSUE THREAD

**Issue by immae** [nix-community/disko#244] opened 2023-05-23 22:07 UTC
This is a feature request.

Currently disko layout creation happens only in oneshot at "initialization": if we want to rearrange the layout after creation we need to do the action manually, and reflect that in the disco configuration for mounting, with the risk of not exactly replicating the changes.

The generic case is probably impossible to handle, and probably not worth the trouble (changing the layout of a disk is not something that happens everyday), but there are two things that could have an added value:

- Some cases (creation of zfs datasets "on-the-fly") could have an "easier" implementation and a quite useful addition

- Other ones could make some checks during activation and verify (best effort) that the layout corresponds to the declared one and show a warning otherwise. This would permit "incremental" computation of a diff between declared and current, until the diff is complete enough to be turned into a set of actions to enforce it.

I’d be interested in participating in starting that kind of development (for ZFS at first for instance ;) ) if that’s part of the wanted direction for that tool

**Comment by dehnert** [comment] 2024-09-26 02:49
I think this is a duplicate of #295 , which was partially implemented in #568 .

**Comment by iFreilicht** [comment] 2024-09-26 09:08
Agreed, thank you!

**Closed** 2024-09-26 09:08 UTC
