### ISSUE TITLE
Example boot-raid1.nix does not work as expected

### ISSUE THREAD

**Issue by Bouni** [nix-community/disko#667] opened 2024-06-06 07:45 UTC
I have a board with two NVMe disks on which I want to install nixos and use the disko boot-raid1.nix example.
That works as expected but if I remove one disk the system dos no longer boot.

This is the error I see:

![IMG_20240606_092022](https://github.com/nix-community/disko/assets/948965/6bc9b3e6-b23a-468e-8de3-dc5588ee78e5)

The disko config is exactly as in the example, I've just replaced `sda` and `sdb` with `nvme0n1` and `nvme1n1`

Is there anything I'm doing wrong?

**Comment by Mic92** [comment] 2024-06-07 14:38
Looks correct in principle. Can you assemble the raid from a rescue system?

```
mdadm --assemble /dev/md1 /dev/nvme0n1
```

**Comment by Bouni** [comment] 2024-06-13 11:00
@Mic92 Does rescue System mean that I have to boot from lets say an USB disk?

If thats the case I had a major misconception of how this works. I hopes that if one disk failes the system would still boot from the working one and I get some kin of message that a disk failed and by replacing the failed disk I could simply sync the raid again and call it a day.

But that way I still have to go to the basement and manually fix the system ...


Is there a way to have the boot partintion on an internal USB disk (the board has a internal USB connector that could be used for this) and having a raid 0 over the two NVMe disks?

My idea is that the boot partiotion is just used for booting the system and my data on the NVMe disks is mirrored.
Loosing one of the two disks would still allow me to boot the system and fix the issue by relacing the disk.
Again a misconception on my side here?

**Comment by Mic92** [comment] 2024-06-13 11:16
It would be great if it would just boot with one disk, but I was just trying to troubleshoot the root cause here.

**Comment by Bouni** [comment] 2024-06-13 11:20
So would a zfs raid work the way I thought this one would do?

I'm open for all solutions to my future problems 😅

**Comment by Bouni** [comment] 2024-06-13 11:43
I guess if the disk fails while the system is running everything continues to work. But in order to repair the raid (which requires installing a new disk obviously) a reboot is required which leads to a broken system unless I boot from a rescue system, right?

**Comment by Mic92** [comment] 2024-06-14 07:17
I don't know. My intuition says it should be possible to assemble a raid with just one disk member and I don't know why this doesn't work at boot time. Using a rescue system, was just my recommendation to maybe get better error messages to find why find out why it's not working as expected.

**Comment by Mic92** [comment] 2024-06-14 07:18
I am going to close this now, because I don't see things just now within disko we can fix. It's more likely that this is an issue in the mdraid module of NixOS. We can continue to discuss this though.

**Closed by Mic92** 2024-06-14 07:18 UTC
