### ISSUE TITLE
ZFS: inherited `mountpoint=legacy` is not considered for `zfs_fs`

### ISSUE THREAD

**Issue by nativerv** [nix-community/disko#703] opened 2024-07-12 12:42 UTC
Properties of parent dataset in ZFS are inherited by children. When a dataset has `options.mountpoint = "legacy";`, it's children are `legacy` too, but `disko` incorrectly uses `-o zfsutil`/`zfs mount` on them (it considers only self `options.mountpoint` from each `zfs_fs`, which is a workaround currently, but causes repetition):

```
+ mount pool/docker /mnt/var/lib/docker -o X-mount.mkdir -o defaults -o zfsutil -t zfs
filesystem 'pool/docker' cannot be mounted using 'zfs mount'.
Use 'zfs set mountpoint=/mnt/var/lib/docker' or 'mount -t zfs pool/docker /mnt/var/lib/docker'.
See zfs(8) for more information.
+ rm -rf /tmp/tmp.0BAzCacaid
```

**Comment by iFreilicht** [comment] 2024-09-20 23:28
As far as I can tell, the issue is in [this line](https://github.com/nix-community/disko/blob/51994df8ba24d5db5459ccf17b6494643301ad28/lib/types/zfs_fs.nix#L110), which determines whether to insert `-o zfsutil` based on the configuration value.

Instead, the value should be determined at runtime, and the insertion of this option should depend on that runtime value.

**Comment by Enzime** [comment] 2024-09-21 05:59
Closing this as a duplicate of #560 

I don't think this will be easy to change at runtime because mount options get set in the NixOS config under `fileSystems` and get baked into `/etc/fstab`

**Closed by Enzime** 2024-09-21 05:59 UTC
Labels: bug, good first issue, contributions welcome
