### ISSUE TITLE
Support depends attribute

### ISSUE THREAD

**Issue by ktrinh-anduril** [nix-community/disko#141] opened 2023-02-03 21:44 UTC
Hello, is there plan to support the `depends` attribute that nixos filesystems option support? I think right now the mount order is only determined by parsing the name of the mount point for parent and child relationship but it would be nice to also have the option to explicitly specify the dependency relationship.

**Comment by Mic92** [comment] 2023-02-20 21:20
Can you add some example where this would be useful to have?

**Comment by oddlama** [comment] 2023-04-29 16:02
I'd also need this and I can provide an example. I am using the layout given below together with impermanence. The issue is that the datasets are created and mounted by disko in alphabetical order, which in the case of mounting is the wrong way around. Currently `local/nix` is mounted to `/nix` first, but is then shadowed by mounting `local/root` to `/`. So here I'd need an additional dependency (or a more complicated automatic resolution that inspects mountpoints like ZFS does internally).

Creation order should also be (partly) determined by this, since the dataset creation will implicitly mount them when using the non-legacy ZFS mountpoints (i.e. when setting `options.mountpoint`). To avoid issues with conflicting creation and mount order, one could also export the zpool after creating the datasets, since `zpool import` will then do the correct thing.

```nix
rpool = {
  datasets = {
    "local".type = "zfs_fs";
    "local/root" = {
      type = "zfs_fs";
      postCreateHook = "zfs snapshot rpool/local/root@blank";
      options.canmount = "on";
      mountpoint = "/";
    };
    "local/nix" = {
      type = "zfs_fs";
      options.canmount = "on";
      mountpoint = "/nix";
    };
    # ... some other persistent datasets
  };
};
```

**Comment by Lassulus** [comment] 2023-04-29 16:27
huh, maybe there is a bug. mounting should happen alphabetically sorted by mountpoint. but maybe that is not true for if mounting it via NixOS. for creation exporting and reimporting sounds like a good solution

**Comment by oddlama** [comment] 2023-04-29 16:37
You are right, this only seems to affect datasets mounted on creation, the mounting section seems to be sorted correctly.

I just noticed that the import statements are not using `-l` to load required encryption keys, which would be necessary to support encrypted datasets with `keylocation=prompt` when doing the export import workaround. Currently the datasets are still unlocked due to creation.

**Comment by oddlama** [comment] 2023-04-29 20:21
Turns out the export-import workaround doesn't work that easily since `zpool export` fails when there are shadowed datasets (it tries to unmount in the correct reversed order, which won't work). Instead we should create datasets with `-u` to prevent mounting them in the first place. Then the mounting logic can mount them as usual. I've created #218 that addresses that.

**Comment by Lassulus** [comment] 2023-04-29 22:57
so still no usecase for depends attribute? people can still set them over 'fileSystems.*.depends` directly so not sure if we should support them in disko at all?

**Comment by oddlama** [comment] 2023-04-30 10:44
I agree, you should be able to do everything just by using the nixos attribute. So I'd vote for closing this, and if someone finds a usecase that cannot be covered with `fileSystems` alone they can open a new issue describing the situation.

**Closed** 2023-04-30 13:00 UTC
