### ISSUE TITLE
How do I actually create a zfs pool on a running system?

### ISSUE THREAD

**Issue by ameyp** [nix-community/disko#525] opened 2024-01-31 15:43 UTC
I have an existing machine running NixOS, so this is not a fresh-installation scenario. I have a couple of disks plugged into it, and I'd like to create a ZFS pool with them and start using them. My machine is managed with flakes, so I followed the flake-based setup, and added this to my configuration:

```
disko.devices = {
    disk = {
      "disk1" = {
        type = "disk";
        device = "/dev/disk/by-id/ata-1234";
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "storage";
              };
           };
          };
        };
      };
      "disk2" = {
        type = "disk";
        device = "/dev/disk/by-id/scsi-5678";
        content = {
          type = "gpt";
          partitions = {
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "storage";
              };
            };
          };
        };
      };
    };
    zpool = {
      "storage" = {
        type = "zpool";
        mode = "mirror";
        mountpoint = "/mnt/nas/storage";
        rootFsOptions = {
          encryption = "on";
          keyformat = "passphrase";
          keylocation = "prompt";
          compression = "lz4";
          atime = "off";
          recordsize = "1M";
          xattr = "sa";
          acltype = "posixacl";
          ashift = "12";
        };

        datasets = {
          dataset = {
            type = "zfs_fs";
            mountpoint = "/mnt/nas/storage/backups";
          };
        };
      };
    };
  }
```

When I run `sudo nixos-rebuild --flake ".#default" switch`, my system takes several seconds and then goes into emergency mode. In `journalctl -xb`, I see that the service `zfs-import-storage.service` failed. That service seems to be trying to import the `storage` ZFS pool, but nothing seems to actually be creating the pool. I thought `disko` would automatically create the pool too, but that doesn't seem to be the case. I can't create it manually either since the scripts are [no longer created](https://github.com/nix-community/disko/issues/454). I feel like I'm missing something - what's the flow supposed to be for creating a pool and using it on a system that already has NixOS installed?

**Comment by ameyp** [comment] 2024-01-31 16:45
The same question applies to datasets too - `switch` doesn't create datasets in an existing, imported pool.

**Comment by Mic92** [comment] 2024-02-01 04:17
You can use the disko cli to create this at runtime:

It is also in nixpkgs-unstable:

This one will just print the script for formatting
```
disko --dry-run -m format --flake /home/joerg/.homesick/repos/dotfiles#turingmachine
```

If you are happy with the generated script, you can drop the `--dry-run` flag

```
disko -m format --flake /home/joerg/.homesick/repos/dotfiles#turingmachine
```

If you use the `disko` mode than it will mount the freshly formatted disks to /mnt.

**Comment by Mic92** [comment] 2024-02-01 05:31
This is not implemented. Duplicate of https://github.com/nix-community/disko/issues/524

**Closed by Mic92** 2024-02-01 05:31 UTC
