### ISSUE TITLE
What's wrong with the config below?

### ISSUE THREAD

**Issue by nikolay** [nix-community/disko#354] opened 2023-09-10 05:19 UTC
I get this error:

![image](https://github.com/nix-community/disko/assets/2882/f34b2673-5f7d-4954-be5b-f2f6fb7582e9)

With this config:
```nix
{
  disks,
  lib,
  ...
}: {
  disko.devices = {
    disk = lib.genAttrs disks (device: {
      type = "disk";
      name = lib.removePrefix "_" (builtins.replaceStrings ["/"] ["_"] device);
      device = device;
      content = {
        type = "gpt";
        partitions =
          (
            lib.mkIf (device == (builtins.elemAt disks 0)) {
              esp = {
                type = "EF00";
                size = "512M";
                content = {
                  type = "filesystem";
                  format = "vfat";
                  mountpoint = "/boot";
                };
              };
            }
          )
          // {
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "zroot";
              };
            };
          };
      };
    });
    zpool = {
      zroot = {
        type = "zpool";
        mode = "raidz";
        rootFsOptions = {
          compression = "zstd";
          "com.sun:auto-snapshot" = "false";
        };
        datasets = {
          "data" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
          "ROOT" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
          "ROOT/empty" = {
            type = "zfs_fs";
            mountpoint = "/";
            options.mountpoint = "legacy";
            postCreateHook = ''
              zfs snapshot zroot/ROOT/empty@start
            '';
          };
          "ROOT/nix" = {
            type = "zfs_fs";
            mountpoint = "/nix";
            options.mountpoint = "legacy";
          };
        };
      };
    };
  };
}
```

**Comment by nikolay** [comment] 2023-09-10 06:03
The issue was my deployment script. Sorry.

**Comment by nikolay** [comment] 2023-09-10 06:20
Never mind, it wasn't the deployment script.

**Comment by phaer** [comment] 2023-09-10 09:32
>             lib.mkIf (device == (builtins.elemAt disks 0)) {

I believe you can just use `if (device == (builtins.elemAt disks 0)) then ... else ...`.

**Comment by nikolay** [comment] 2023-09-10 15:46
@phaer Yeah, sorry. My last version, which works, is this one:

```nix
{
  disks ? ["/dev/sda" "/dev/sdb" "/dev/sdc"],
  lib,
  ...
}: let
  zfs = {
    type = "zfs";
    pool = "zroot";
  };
in {
  disko.devices = {
    disk = lib.genAttrs disks (device: {
      type = "disk";
      name = lib.removePrefix "_" (builtins.replaceStrings ["/"] ["_"] device);
      device = device;
      content =
        if (device == (builtins.elemAt disks 0))
        then {
          type = "gpt";
          partitions = {
            esp = {
              type = "EF00";
              size = "512M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            zfs = {
              size = "100%";
              content = zfs;
            };
          };
        }
        else zfs;
    });
    zpool = {
      zroot = {
        type = "zpool";
        mode = "raidz";
        rootFsOptions = {
          compression = "zstd";
          "com.sun:auto-snapshot" = "false";
        };
        mountpoint = "/";
        postCreateHook = "zfs snapshot zroot@blank";
        datasets = {
          "root" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
        };
      };
    };
  };
}
```

So, I guess, some of the examples don't really work, i.e. those having `partitions` with just `zfs`.

Yet, not the issue is that `bootclt` fails:

![image](https://github.com/nix-community/disko/assets/2882/b17a990e-0733-498d-a92d-3103d9cd931b)

**Comment by phaer** [comment] 2023-09-10 18:14
> So, I guess, some of the examples don't really work, i.e. those having partitions with just zfs.

Did you test the examples to verify? If so, can you post a log? :)

> Yet, not the issue is that bootctl fails:

It says that /boot does not exist - did you check the log above whether it actually gets created and mounted? You should see creation and mount commands with --debug.

**Comment by nikolay** [comment] 2023-09-10 20:20
@phaer It wasn't getting created, and I'm not sure how I've fixed it, but it works now.  All my code is here: https://github.com/nikolay/zfs-on-nix-test

I'm basically trying to run Nixos on [Scaleway Dedibox](https://www.scaleway.com/en/docs/faq/dedibox/), but I'm a total noob when it comes to Nix and ZFS.

Now, the error is different: 

![image](https://github.com/nix-community/disko/assets/2882/e3484c46-cca3-42bf-9c54-7e13ecaec6bb)

**Comment by nikolay** [comment] 2023-09-10 21:31
@phaer Unfortunately, `/boot` randomly does not mount during the installation. 😒 The second time I ran the script, it failed again. I am a little concerned about `nixos-install` not failing when a critical part fails.

**Comment by iFreilicht** [comment] 2024-10-16 15:40
For posterity, I believe the issue is how you define your zpool:

```nix
    zpool = {
      zroot = {
        type = "zpool";
        mode = "raidz";
        rootFsOptions = {
          compression = "zstd";
          "com.sun:auto-snapshot" = "false";
        };
        postCreateHook = "zfs snapshot zroot@blank";
        datasets = {
          "root" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
        };
      };
 ```
 
You shouldn't mount the rootFS at `/`, that's what the root dataset is for. Instead, try:

```
    zpool = {
      zroot = {
        type = "zpool";
        mode = "raidz";
        rootFsOptions = {
          compression = "zstd";
          "com.sun:auto-snapshot" = "false";
        };
        postCreateHook = "zfs snapshot zroot@blank";
        datasets = {
          "root" = {
            type = "zfs_fs";
            options.mountpoint = "/";
          };
        };
      };
 ```
 
 I'm assuming that you've either solved this issue since last year or have given up, so I'll close this for now to keep our board tidy. However, if you're still working on this and this couldn't solve your issue, feel free to re-open it!

**Closed by iFreilicht** 2024-10-16 15:40 UTC
Labels: question
